#!/bin/sh
# Copyright 2005-2007 Stefan Lippers-Hollmann <s.l-h@gmx.de>
# GPL2

[ "$(id -u)" -ne 0 ] && exec su-me $0 "$@"

# override tool behaviour through distro-defaults
FLL_DISTRO_MODE="installed"
FLL_LIVE_USER="sidux"
FLL_MOUNTPOINT="/fll/SIDUX"

[ -r /etc/default/distro ] && . /etc/default/distro

if [ "$FLL_DISTRO_MODE" = "live" ]; then
	while grep -q '^$FLL_LIVE_USER:\*:' /etc/shadow; do
		echo "Set password for user \"$FLL_LIVE_USER\""
		passwd ${FLL_LIVE_USER}
	done
fi

[ -e /etc/ssh/ssh_host_rsa_key ] || ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C '' -N ''
[ -e /etc/ssh/ssh_host_dsa_key ] || ssh-keygen -q -t dsa -f /etc/ssh/ssh_host_dsa_key -C '' -N ''

if ! pidof sshd &>/dev/null; then
	[ -x /etc/init.d/ssh ] && /etc/init.d/ssh start
fi

exec /usr/sbin/dpkg-reconfigure freenx

