#!/bin/sh

[ "$UID" -ne 0 ] && exec kanotix-su $0 "$@"

if [ -e /etc/sysconfig/live -o -d /KNOPPIX ]; then
	# we are in live mode, so act appropriately

	if grep -q unionfs /proc/mounts; then
		echo Unionfs found.
	else
		echo Activating Unionfs now.
		mkdir -p /tmp/union
		mount -t unionfs -o dirs=/tmp/union/:/KNOPPIX /none /KNOPPIX/ 2>&1 >/dev/null
	fi
	
	while grep -q '^knoppix:\*:' /etc/shadow; do
		echo "Set password for user 'knoppix'"
		passwd knoppix
	done
fi

[ -e /etc/ssh/ssh_host_rsa_key ] || ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C '' -N ''
[ -e /etc/ssh/ssh_host_dsa_key ] || ssh-keygen -q -t dsa -f /etc/ssh/ssh_host_dsa_key -C '' -N ''

if ! pidof sshd &>/dev/null; then
	[ -x /etc/init.d/ssh ] && /etc/init.d/ssh start
fi

exec /usr/sbin/dpkg-reconfigure freenx

